"""add_ondelete cascade tabla speaker y session

Revision ID: 8a86abface9d
Revises: 48c6562719d5
Create Date: 2026-01-13 20:58:15.841255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8a86abface9d"
down_revision: Union[str, Sequence[str], None] = "48c6562719d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "time_slots", "start_time", existing_type=postgresql.TIME(), nullable=True
    )
    op.alter_column(
        "time_slots", "end_time", existing_type=postgresql.TIME(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "time_slots", "end_time", existing_type=postgresql.TIME(), nullable=False
    )
    op.alter_column(
        "time_slots", "start_time", existing_type=postgresql.TIME(), nullable=False
    )
    # ### end Alembic commands ###
