"""add_ondelete_cascade_to_session_speaker

Revision ID: e02d296132c3
Revises: a82fe8125369
Create Date: 2026-01-07 19:39:22.259607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e02d296132c3"
down_revision: Union[str, Sequence[str], None] = "a82fe8125369"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
