"""add_ondelete_cascade_to_session_speaker

Revision ID: 48c6562719d5
Revises: e02d296132c3
Create Date: 2026-01-08 09:26:37.747774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "48c6562719d5"
down_revision: Union[str, Sequence[str], None] = "e02d296132c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "time_slots",
        "start_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Time(),
        existing_nullable=False,
    )
    op.alter_column(
        "time_slots",
        "end_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Time(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "time_slots",
        "end_time",
        existing_type=sa.Time(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "time_slots",
        "start_time",
        existing_type=sa.Time(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
