"""complete_cascade_deletes

Revision ID: 41023ea0b2ab
Revises: 15ae2d9787eb
Create Date: 2026-01-31 16:56:34.744406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41023ea0b2ab'
down_revision: Union[str, Sequence[str], None] = '15ae2d9787eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'event_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('sessions', 'time_slot_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('sessions_event_id_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_time_slot_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'time_slots', ['time_slot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sessions', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.alter_column('time_slots', 'event_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('time_slots_event_id_fkey'), 'time_slots', type_='foreignkey')
    op.create_foreign_key(None, 'time_slots', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_slots', type_='foreignkey')
    op.create_foreign_key(op.f('time_slots_event_id_fkey'), 'time_slots', 'events', ['event_id'], ['id'])
    op.alter_column('time_slots', 'event_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_time_slot_id_fkey'), 'sessions', 'time_slots', ['time_slot_id'], ['id'])
    op.create_foreign_key(op.f('sessions_event_id_fkey'), 'sessions', 'events', ['event_id'], ['id'])
    op.alter_column('sessions', 'time_slot_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sessions', 'event_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
