"""fix_event_deletion_cascade

Revision ID: 15ae2d9787eb
Revises: 8a86abface9d
Create Date: 2026-01-31 16:53:52.673591

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15ae2d9787eb"
down_revision: Union[str, Sequence[str], None] = "8a86abface9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event_registrations", "event_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        op.f("event_registrations_event_id_fkey"),
        "event_registrations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "event_registrations", "events", ["event_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "session_registrations", "session_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        op.f("session_registrations_session_id_fkey"),
        "session_registrations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "session_registrations",
        "sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "session_registrations", type_="foreignkey")
    op.create_foreign_key(
        op.f("session_registrations_session_id_fkey"),
        "session_registrations",
        "sessions",
        ["session_id"],
        ["id"],
    )
    op.alter_column(
        "session_registrations", "session_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_constraint(None, "event_registrations", type_="foreignkey")
    op.create_foreign_key(
        op.f("event_registrations_event_id_fkey"),
        "event_registrations",
        "events",
        ["event_id"],
        ["id"],
    )
    op.alter_column(
        "event_registrations", "event_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
